project_id = "rdymuwbotklotlxqiwyc"

[functions.send-enrollment-notification]
verify_jwt = false

[functions.send-bulk-email]
verify_jwt = false

[functions.send-visit-reminders]
verify_jwt = false

[functions.send-after-visit-email]
verify_jwt = false

[functions.send-after-visit-auto]
verify_jwt = false